import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "../styles/globals.scss";

import BootstrapClient from "@/components/BootstrapClient";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { ModalContextProvider } from "@/context/modalContext";
import { CartContextProvider } from "@/context/cartContext";
import { CartDrawerContextProvider } from "@/context/cartDrawerContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<CartContextProvider>
				<CartDrawerContextProvider>
					<ModalContextProvider>
						<body style={{ minHeight: '100vh' }} className={`${inter.className} d-flex flex-column  background-pattern-crossword`}>
							<Header />

							<main className="flex-grow-1 overflow-hidden">

								{children}

							</main>

							<Footer />

							<BootstrapClient />
						</body>
					</ModalContextProvider>
				</CartDrawerContextProvider>
			</CartContextProvider>
		</html>
	);
}
